import { test, expect, type Page } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import { resolve } from 'node:path'

const screenshots = resolve('../.impeccable/review')
mkdirSync(screenshots, { recursive: true })

async function capture(page: Page, name: string) {
  await expect(page.locator('.toast')).toHaveCount(0, { timeout: 8000 })
  await page.evaluate(async () => {
    await document.fonts.ready
    ;(document.activeElement as HTMLElement)?.blur()
    window.scrollTo(0, 0)
  })
  await page.screenshot({ path: `${screenshots}/${name}.png`, fullPage: true, animations: 'disabled' })
}

test('desktop and mobile use real catalog data and have no overflow', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const response = await request.get('/api/tasks?limit=100')
  expect(response.ok()).toBeTruthy()
  const tasks = await response.json()
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'От задачи — к результату.' })).toBeVisible()
  await expect(page.locator('.task-card').first()).toBeVisible()
  await expect(page.locator('.overview-stats strong').first()).toHaveText(String(tasks.length))
  await page.evaluate(() => document.fonts.ready)
  await capture(page, 'desktop')
  await page.goto('/catalog')
  await expect(page.locator('.task-card').first()).toBeVisible()
  await page.getByLabel('Сортировка').selectOption('rating_asc')
  await expect(page.locator('.task-card .small-score').first()).toHaveText(`${Math.min(...tasks.map((task: any) => task.rating.score))}/100`)
  await page.getByLabel('Уровень готовности').selectOption('ready')
  await expect(page.locator('.task-card').first()).toBeVisible()
  for (const text of await page.locator('.task-card .small-score').allTextContents()) expect(Number(text.split('/')[0])).toBeGreaterThanOrEqual(70)
  await page.getByLabel('Тема задачи').fill('несуществующая-тема-для-проверки')
  await page.getByRole('button', { name: 'Применить тему' }).click()
  await expect(page.getByRole('heading', { name: 'По этим условиям задач пока нет' })).toBeVisible()
  await page.getByRole('button', { name: 'Показать все задачи' }).click()
  await expect(page.locator('.task-card').first()).toBeVisible()
  await capture(page, 'catalog')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.task-card').first()).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await capture(page, 'mobile')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Открыть меню' }).click()
  await expect(page.getByRole('navigation')).toBeVisible()
  await page.getByRole('link', { name: 'Каталог задач', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Найдите свою задачу' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  expect(errors).toEqual([])
})

test('complete business → team → manual decisions journey', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const marker = Date.now().toString().slice(-6)
  await page.goto('/tasks/new')
  await page.getByLabel('Опишите задачу или проблему').fill('Контекст: Мастерская получает заявки на ремонт в разных чатах')
  await page.getByLabel('Тема задачи').fill('автоматизация')
  await capture(page, 'create')
  await page.getByRole('button', { name: 'Разобрать задачу' }).click()
  await expect(page.getByRole('heading', { name: 'Анализ описания готов' })).toBeVisible()
  await expect(page.locator('.question-block')).toHaveCount(3)
  await page.getByLabel('Какую проблему нужно решить?').fill('Объединить заявки и видеть статус ремонта')
  await page.getByLabel('Какой конкретный результат должна предоставить команда?').fill('Реестр заявок с поиском и статусами')
  await page.getByLabel('Как вы проверите, что задача решена успешно?').fill('Заявки находятся по номеру, изменение статуса сохраняется')
  await capture(page, 'clarification')
  await page.getByRole('button', { name: 'Собрать карточку' }).click()
  await expect(page.getByRole('heading', { name: 'Ваша задача обретает форму' })).toBeVisible()
  const id = Number(page.url().match(/tasks\/(\d+)/)![1])
  await page.getByLabel('Название', { exact: true }).fill(`Реестр заявок мастерской · ${marker}`)
  await page.getByLabel('Пользователи', { exact: true }).fill('Администраторы мастерской')
  await page.getByLabel('Данные и материалы', { exact: true }).fill('Обезличенная таблица текущих заявок')
  await page.getByLabel('Ограничения', { exact: true }).fill('Прототип за пять часов, без платных сервисов')
  await page.getByLabel('Контакт', { exact: true }).fill('workshop@example.com')
  await page.getByLabel('Формат взаимодействия', { exact: true }).fill('Короткая встреча на старте и демонстрация в конце')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await expect(page.locator('.rating-total > strong')).toHaveText('100 / 100')
  await capture(page, 'editor')
  await page.getByLabel('Данные и материалы', { exact: true }).fill('TBD')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await expect(page.locator('.rating-total > strong')).toHaveText('80 / 100')
  await page.getByRole('button', { name: 'Подтвердить карточку' }).click()
  await expect(page.getByText('Карточка подтверждена', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Опубликовать задачу' }).click()
  await expect(page).toHaveURL(new RegExp(`/tasks/${id}$`))
  const persisted = await (await request.get(`/api/tasks/${id}`)).json()
  expect(persisted.status).toBe('published')
  expect(persisted.rating.score).toBe(80)
  await page.getByRole('button', { name: 'Команда', exact: true }).click()
  await capture(page, 'details')
  for (const name of [`Мастерская решений ${marker}`, `Команда практики ${marker}`]) {
    await page.getByRole('link', { name: 'Предложить решение', exact: true }).first().click()
    await page.getByLabel('Название команды').fill(name)
    await page.getByLabel('Идея решения').fill('Локальный реестр заявок с поиском')
    await page.getByLabel('План работы').fill('Уточнить поля, реализовать поиск, проверить изменение статусов')
    await page.getByLabel('Оценка времени').fill('5 часов')
    await page.getByLabel('Ссылка на прототип').fill('https://example.com/workshop')
    await capture(page, 'proposal-form')
    await page.getByRole('button', { name: 'Отправить предложение' }).click()
    await expect(page.getByRole('heading', { name: 'Ваше решение — в деле.' })).toBeVisible()
    await page.getByRole('link', { name: 'Вернуться к задаче' }).click()
  }
  await page.getByRole('button', { name: 'Бизнес', exact: true }).click()
  await page.getByRole('link', { name: 'Смотреть предложения' }).click()
  await expect(page.locator('.proposal-card')).toHaveCount(2)
  await capture(page, 'proposals')
  let proposals = await (await request.get(`/api/tasks/${id}/proposals`)).json()
  expect(proposals.every((proposal: any) => proposal.status === 'pending')).toBeTruthy()
  const first = page.locator('.proposal-card').first()
  await first.getByRole('button', { name: 'Принять команду' }).click()
  await first.getByRole('button', { name: 'Да, принять' }).click()
  await expect(first.getByText('Команда выбрана', { exact: true })).toBeVisible()
  const second = page.locator('.proposal-card').nth(1)
  await second.getByRole('button', { name: 'Отклонить', exact: true }).click()
  await second.getByRole('button', { name: 'Да, отклонить' }).click()
  await expect(second.getByText('Отклонено', { exact: true })).toBeVisible()
  proposals = await (await request.get(`/api/tasks/${id}/proposals`)).json()
  expect(proposals.map((proposal: any) => proposal.status)).toEqual(['accepted', 'rejected'])
  expect(errors).toEqual([])
})

test('network errors preserve input and recover; no fabricated fallback cards', async ({ page }) => {
  await page.route('**/api/tasks?*', route => route.abort())
  await page.goto('/catalog')
  await expect(page.getByRole('alert')).toContainText('Не удалось связаться с сервером')
  await expect(page.locator('.task-card')).toHaveCount(0)
  await page.unroute('**/api/tasks?*')
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.locator('.task-card').first()).toBeVisible()
  await page.goto('/tasks/new')
  await page.getByLabel('Опишите задачу или проблему').fill('Текст сохраняется при сетевой ошибке')
  await page.route('**/api/tasks', route => route.abort())
  await page.getByRole('button', { name: 'Разобрать задачу' }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByLabel('Опишите задачу или проблему')).toHaveValue('Текст сохраняется при сетевой ошибке')
  await expect(page.getByRole('button', { name: 'Разобрать задачу' })).toBeEnabled()
})

test('zero-score task can be published and receives a proposal through UI', async ({ page, request }) => {
  const task = await (await request.post('/api/tasks', { data: { description: 'не знаю', topic: 'исследование' } })).json()
  await request.post(`/api/tasks/${task.id}/answers`, { data: { answers: ['need', 'expected_result', 'success_criteria'].map(field => ({ field, answer: '' })) } })
  await page.goto(`/tasks/${task.id}/edit`)
  await expect(page.locator('.rating-total > strong')).toHaveText('0 / 100')
  await page.getByRole('button', { name: 'Подтвердить карточку' }).click()
  await page.getByRole('button', { name: 'Опубликовать задачу' }).click()
  await expect(page).toHaveURL(new RegExp(`/tasks/${task.id}$`))
  await page.getByRole('button', { name: 'Команда', exact: true }).click()
  await page.getByRole('link', { name: 'Предложить решение', exact: true }).first().click()
  await page.getByLabel('Название команды').fill('Исследовательская команда')
  await page.getByLabel('Идея решения').fill('Начнём с интервью')
  await page.getByLabel('План работы').fill('Выявить потребность и согласовать результат')
  await page.getByLabel('Оценка времени').fill('1 час')
  await page.getByRole('button', { name: 'Отправить предложение' }).click()
  await expect(page.getByRole('heading', { name: 'Ваше решение — в деле.' })).toBeVisible()
})
