import { test, expect, type Page } from '@playwright/test'

function watchErrors(page: Page) {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  page.on('response', response => { if (response.url().includes('/api/') && response.status() >= 500) errors.push(`HTTP ${response.status()}: ${response.url()}`) })
  return errors
}

test('integration: complete user flow survives reload at each checkpoint', async ({ page, request }, testInfo) => {
  const errors = watchErrors(page)
  page.on('dialog', dialog => dialog.accept())
  const topic = `qa-${Date.now()}`
  const title = `Заявки мастерской ${topic}`
  await page.goto('/tasks/new')
  await page.getByLabel('Опишите задачу или проблему').fill('Заявки мастерской теряются в чатах')
  await page.getByLabel('Тема задачи').fill(topic)
  await page.reload()
  await expect(page.getByLabel('Опишите задачу или проблему')).toHaveValue('Заявки мастерской теряются в чатах')
  await page.getByRole('button', { name: 'Разобрать задачу' }).click()
  await expect(page.locator('.question-block')).toHaveCount(3)
  const id = Number(page.url().match(/tasks\/(\d+)/)![1])
  const questions = await (await request.get(`/api/tasks/${id}/questions`)).json()
  expect(questions.questions.map((q: { field: string }) => q.field)).toEqual(['need', 'expected_result', 'success_criteria'])
  await page.getByLabel('Какую проблему нужно решить?').fill('Собрать заявки в одном реестре')
  await page.reload()
  await expect(page.getByLabel('Какую проблему нужно решить?')).toHaveValue('Собрать заявки в одном реестре')
  await page.getByLabel('Какой конкретный результат должна предоставить команда?').fill('Реестр с поиском и статусами')
  await page.getByLabel('Как вы проверите, что задача решена успешно?').fill('Все тестовые заявки находятся по номеру')
  await page.getByRole('button', { name: 'Собрать карточку' }).click()
  await expect(page.locator('.rating-total > strong')).toHaveText('50 / 100')
  await expect(page.locator('.rating-level')).toHaveText('Часть описана')
  await page.getByLabel('Название', { exact: true }).fill(title)
  await page.getByLabel('Данные и материалы', { exact: true }).fill('Обезличенный CSV с заявками')
  await page.reload()
  await expect(page.getByLabel('Данные и материалы', { exact: true })).toHaveValue('Обезличенный CSV с заявками')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await expect(page.locator('.rating-total > strong')).toHaveText('70 / 100')
  await expect(page.locator('.rating-level')).toHaveText('Много деталей')
  await page.reload()
  await expect(page.locator('.rating-total > strong')).toHaveText('70 / 100')
  await page.getByRole('button', { name: 'Подтвердить карточку' }).click()
  await expect(page.getByText('Карточка подтверждена', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Опубликовать задачу' }).click()
  await expect(page).toHaveURL(new RegExp(`/tasks/${id}$`))
  await page.getByRole('button', { name: 'Команда', exact: true }).click()
  await page.getByRole('link', { name: 'Каталог задач', exact: true }).click()
  await page.getByLabel('Тема задачи').fill(topic.toUpperCase())
  await page.getByRole('button', { name: 'Применить тему' }).click()
  await page.getByLabel('Полнота описания', { exact: true }).selectOption('ready')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Команда', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.task-card')).toHaveCount(1)
  await page.locator('.task-card').filter({ hasText: title }).click()
  await expect(page.locator('.rating-total > strong')).toHaveText('70 / 100')
  await page.getByRole('link', { name: 'Предложить решение', exact: true }).first().click()
  await page.getByLabel('Название команды').fill('Integration Team')
  await page.getByLabel('Идея решения').fill('Сделаем локальный реестр')
  await page.getByLabel('План работы').fill('Разобрать CSV, создать форму, проверить поиск')
  await page.getByLabel('Оценка времени').fill('5 часов')
  await page.reload()
  await expect(page.getByLabel('План работы')).toHaveValue('Разобрать CSV, создать форму, проверить поиск')
  await page.getByRole('button', { name: 'Отправить предложение' }).click()
  await expect(page.getByRole('heading', { name: 'Ваше решение — в деле.' })).toBeVisible()
  await page.getByRole('link', { name: 'Вернуться к задаче' }).click()
  await page.getByRole('button', { name: 'Бизнес', exact: true }).click()
  await page.getByRole('link', { name: 'Смотреть предложения' }).click()
  await expect(page.locator('.proposal-card')).toHaveCount(1)
  await expect(page.locator('.proposal-card')).toContainText('Разобрать CSV, создать форму, проверить поиск')
  await page.getByRole('button', { name: 'Принять команду' }).click()
  await page.getByRole('button', { name: 'Да, принять' }).click()
  await expect(page.getByText('Вы выбрали команду «Integration Team»')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Вы выбрали команду «Integration Team»')).toBeVisible()
  const task = await (await request.get(`/api/tasks/${id}`)).json()
  const proposals = await (await request.get(`/api/tasks/${id}/proposals`)).json()
  expect(task.status).toBe('published')
  expect(task.rating.score).toBe(70)
  expect(proposals).toHaveLength(1)
  expect(proposals[0].status).toBe('accepted')
  expect(errors).toEqual([])
  await testInfo.attach('persisted-demo', { body: JSON.stringify({ task_id: id, proposal_id: proposals[0].id, score: 70 }), contentType: 'application/json' })
})

test('validation: whitespace, required fields, prototype URL and recoverable API errors', async ({ page, request }) => {
  const runtimeErrors: string[] = []
  page.on('pageerror', error => runtimeErrors.push(error.message))
  await page.goto('/tasks/new')
  await page.getByLabel('Опишите задачу или проблему').fill('   ')
  await expect(page.getByRole('button', { name: 'Разобрать задачу' })).toBeDisabled()
  const tasks = await (await request.get('/api/tasks?limit=1')).json()
  const id = tasks[0].id
  await page.getByRole('button', { name: 'Команда', exact: true }).click()
  await page.goto(`/tasks/${id}/propose`)
  await page.getByRole('button', { name: 'Отправить предложение' }).click()
  expect(await page.locator('#team').evaluate((input: HTMLInputElement) => input.validity.valueMissing)).toBeTruthy()
  await page.getByLabel('Название команды').fill('   ')
  await page.getByLabel('Идея решения').fill('Идея')
  await page.getByLabel('План работы').fill('План')
  await page.getByLabel('Оценка времени').fill('5 часов')
  await page.getByRole('button', { name: 'Отправить предложение' }).click()
  await expect(page.getByRole('alert')).toContainText('Заполните название команды')
  await page.getByLabel('Название команды').fill('Validation Team')
  await page.getByLabel('Ссылка на прототип').fill('javascript:alert(1)')
  expect(await page.locator('#prototype').evaluate((input: HTMLInputElement) => input.checkValidity())).toBeFalsy()
  await page.getByLabel('Ссылка на прототип').fill('')
  const endpoint = `**/api/tasks/${id}/proposals`
  for (const status of [422, 500]) {
    await page.route(endpoint, route => route.request().method() === 'POST' ? route.fulfill({ status, json: { detail: status === 422 ? [{ msg: 'Invalid value' }] : 'Service unavailable' } }) : route.continue())
    await page.getByRole('button', { name: 'Отправить предложение' }).click()
    await expect(page.getByRole('alert')).toBeVisible()
    await expect(page.getByLabel('Идея решения')).toHaveValue('Идея')
    await expect(page.getByRole('button', { name: 'Отправить предложение' })).toBeEnabled()
    await page.unroute(endpoint)
  }
  await page.getByRole('button', { name: 'Отправить предложение' }).click()
  await expect(page.getByRole('heading', { name: 'Ваше решение — в деле.' })).toBeVisible()
  await page.goto('/tasks/2147483647')
  await expect(page.getByRole('alert')).toContainText('Задача не найдена')
  await page.goto('/catalog?level=invalid')
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByLabel('Полнота описания', { exact: true }).selectOption('')
  await expect(page.locator('.task-card').first()).toBeVisible()
  expect(runtimeErrors).toEqual([])
})
