import { test, expect } from '@playwright/test'

test('mobile catalog keeps tasks visible and preserves independent filters', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/catalog')
  await page.getByRole('button', { name: 'Команда', exact: true }).click()
  await expect(page.locator('.task-card').first()).toBeVisible()
  await expect(page.getByLabel('Сортировка')).toBeHidden()
  expect((await page.locator('.task-card').first().boundingBox())!.y).toBeLessThan(440)
  await page.getByRole('button', { name: 'Фильтры', exact: true }).click()
  await expect(page.getByLabel('Сортировка')).toBeVisible()
  await page.getByLabel('Тема задачи').fill('аналитика')
  await page.getByLabel('Сортировка').selectOption('newest')
  // Changing another filter must not erase a theme still being typed.
  await expect(page.getByLabel('Тема задачи')).toHaveValue('аналитика')
  await page.getByRole('button', { name: 'Применить тему' }).click()
  await page.getByLabel('Полнота описания', { exact: true }).selectOption('ready')
  await expect(page.locator('.task-card').first()).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: /^Фильтры/ })).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('button', { name: 'Убрать фильтр полноты описания' })).toBeVisible()
  await page.getByRole('button', { name: 'Убрать тему: аналитика' }).click()
  await expect(page.getByLabel('Тема задачи')).toHaveValue('')
  await expect(page).toHaveURL(/level=ready/)
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click()
  await expect(page).toHaveURL(/\/catalog$/)
  await page.setViewportSize({ width: 320, height: 740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.getByLabel('Сортировка')).toBeVisible()
  await expect(page.getByLabel('Полнота описания', { exact: true })).toBeVisible()
})

test('score meaning is explicit and its accessible name is not duplicated', async ({ page }) => {
  await page.goto('/catalog')
  const card = page.locator('.task-card').first()
  await expect(card).toContainText('Полнота описания:')
  const accessible = await card.ariaSnapshot()
  expect(accessible).toContain('Полнота описания:')
  expect(accessible).not.toContain('progressbar')
  expect(accessible).not.toContain('100/100')
  await card.click()
  await expect(page.getByRole('heading', { name: 'Полнота описания' })).toBeVisible()
  await expect(page.locator('.rating-widget')).toContainText('Ценность и реализуемость идеи здесь не оцениваются')
  await expect(page.locator('.rating-level')).not.toHaveText(/PRIORITY|READY|WORKABLE|DRAFT/i)
})

test('mobile navigation supports keyboard dismissal and route focus', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const menu = page.getByRole('button', { name: 'Открыть меню' })
  await menu.click()
  await expect(page.getByRole('navigation')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()
  await expect(page.getByRole('navigation')).toBeHidden()
  await menu.click()
  await page.getByRole('link', { name: 'Каталог задач', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Найдите свою задачу' })).toBeVisible()
  await expect(page.locator('main')).toBeFocused()
  await expect(page).toHaveTitle(/Каталог/)
})
