import type { TaskPayload } from "./task-payload";
export const emptyTask: TaskPayload = {
  organization: "",
  title: "",
  summary: "",
  problem: "",
  goal: "",
  context: "",
  audience: "",
  deliverables: "",
  constraints: "",
  timeline: "",
  acceptanceCriteria: "",
  skills: [],
};
export const fieldDefinitions = [
  {
    key: "organization",
    label: "Компания или организация",
    hint: "Как представить вашу компанию студентам",
    max: 120,
    step: 0,
  },
  {
    key: "title",
    label: "Название задачи",
    hint: "Панель для отслеживания заявок",
    max: 140,
    step: 0,
  },
  {
    key: "summary",
    label: "Задача в двух предложениях",
    hint: "Что нужно сделать и зачем это бизнесу",
    max: 400,
    step: 0,
    long: true,
  },
  {
    key: "problem",
    label: "Проблема сегодня",
    hint: "Что не работает, кого это затрагивает и к чему приводит",
    max: 2000,
    step: 0,
    long: true,
  },
  {
    key: "goal",
    label: "Желаемый результат",
    hint: "Что изменится после решения задачи",
    max: 1200,
    step: 1,
    long: true,
  },
  {
    key: "audience",
    label: "Пользователи результата",
    hint: "Кто и в какой ситуации будет им пользоваться",
    max: 600,
    step: 1,
  },
  {
    key: "context",
    label: "Данные и контекст",
    hint: "Какие материалы, процессы и решения уже есть",
    max: 1200,
    step: 1,
    long: true,
  },
  {
    key: "deliverables",
    label: "Что команда передаст бизнесу",
    hint: "Например: прототип, исходный код и инструкция",
    max: 1200,
    step: 1,
    long: true,
  },
  {
    key: "constraints",
    label: "Условия и ограничения",
    hint: "Доступы, технологии, бюджет, конфиденциальность",
    max: 1000,
    step: 2,
    long: true,
  },
  {
    key: "timeline",
    label: "Срок выполнения",
    hint: "Например: прототип за 3 недели",
    max: 400,
    step: 2,
  },
  {
    key: "acceptanceCriteria",
    label: "Критерии готовности",
    hint: "Как проверить, что результат решает задачу?",
    max: 1200,
    step: 2,
    long: true,
  },
] as const;
